version: "3.4"

services:
  nginx-server:
    image: nginx:1.17.4-alpine
    restart: always
    container_name: nginx-server
    ports:
      - 9080:80
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./dist:/usr/share/nginx/html
